version: 2

cache_key: &cache_key
  key: v5-opam-deps-{{ checksum "integrations.opam" }}-{{ checksum "ocaml-version" }}

jobs:
  build:
    docker:
      - image: ocaml/opam2:4.11
    environment:
      - TERM: dumb
    branches:
      ignore:
        - cron

    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            sudo apt-get install -y m4
            eval `opam config env`
            opam --version
            ocaml -version
            ocaml -version > ocaml-version
      - restore_cache:
          <<: *cache_key
      - run:
          name: opam dependencies
          command: |
            opam reinstall -y bisect_ppx
            opam install -y --deps-only .
            opam list
      - run:
          name: Run test
          command: |
            eval `opam config env`
            dune exec --instrument-with bisect_ppx ./simple.exe -- circleci
      - run:
          name: Send to Coveralls
          command: |
            eval `opam config env`
            bisect-ppx-report send-to Coveralls
      - run:
          name: Send to Codecov
          command: |
            eval `opam config env`
            bisect-ppx-report send-to Codecov
      - run:
          name: Clean up for caching
          command: |
            opam clean
      - save_cache:
          <<: *cache_key
          paths:
            - ~/.opam/4.11
