version: 2

cache_key: &cache_key
  key: v3-opam-deps-{{ checksum "integrations.opam" }}-{{ checksum "ocaml-version" }}

jobs:
  build:
    docker:
      - image: ocaml/opam2:4.08
    environment:
      - TERM: dumb

    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            sudo apt-get install -y m4
            eval `opam config env`
            opam --version
            ocaml -version
            ocaml -version > ocaml-version
      - restore_cache:
          <<: *cache_key
      - run:
          name: opam dependencies
          command: |
            opam install -y --deps-only .
      - run:
          name: Run test
          command: |
            eval `opam config env`
            dune build ./simple.exe
            dune exec ./simple.exe -- circleci
      - run:
          name: Send to Coveralls
          command: |
            eval `opam config env`
            bisect-ppx-report --send-to Coveralls --repo-token $COVERALLS_REPO_TOKEN
      - run:
          name: Cleanup for caching
          command: |
            opam clean
      - save_cache:
          <<: *cache_key
          paths:
            - ~/.opam/4.08
