name: Test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - uses: avsm/setup-ocaml@master
      - run: opam reinstall -y bisect_ppx
      - run: opam install -y --deps-only .

      - run: opam exec -- dune build ./simple.exe
      - run: opam exec -- dune exec ./simple.exe -- github

      - run: opam exec -- bisect-ppx-report send-to Coveralls
      - run: opam exec -- bisect-ppx-report send-to Codecov
